name: "Vprofile Terraform Destroy"

on:
  push:
    branches:
      - main
    paths:
      - terraform/**

permissions:
  id-token: write

env:
  AWS_REGION: us-east-1  
  EKS_CLUSTER: vprofile-eks  

jobs:
  terraform-destroy:
    name: "Destroy Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::182399687748:role/github-action-OICD
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity

      - name: Terraform Init
        id: Init
        run: terraform init -backend-config="bucket=${{ secrets.BUCKET_TF_STATE }}"

      - name: Terraform Plan Destroy
        id: plan_destroy
        run: terraform plan -destroy -no-color -input=false -out destroy-planfile

      - name: Terraform Destroy
        if: github.ref == 'refs/heads/destroy' && github.event_name == 'push'
        run: terraform apply -destroy -auto-approve -input=false destroy-planfile
