name: Test Secrets
on:
    push:
      branches:
        - main
        - stage
      paths:
        - terraform/**
    pull_request:
      branches:
        - main
      paths:
        - terraform/**
jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log Secrets
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}"